import type { Metadata } from "next";
import "./globals.css";
import ReactQueryProvider from "@/components/providers/reactquery.provider";
import { Toaster } from "@/components/ui/toaster";
import TimeLogProvider from "@/components/providers/time.log.provider";
import RedirectProvider from "@/components/providers/redirect.provider";
import FullScreenProvider from "@/components/providers/fullscreen.provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReactQueryProvider>
        <FullScreenProvider>
          <RedirectProvider>
            <TimeLogProvider>{children}</TimeLogProvider>
          </RedirectProvider>
          <Toaster />
        </FullScreenProvider>
      </ReactQueryProvider>
    </html>
  );
}
