import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "@/components/providers/reactquery.provider";
import { Toaster } from "@/components/ui/toaster";
import { cn } from "@/lib/utils";
import TimeLogProvider from "@/components/providers/time.log.provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReactQueryProvider>
        <body className={cn(inter.className, "min-h-screen h-full")}>
          <TimeLogProvider>{children}</TimeLogProvider>
          <Toaster />
        </body>
      </ReactQueryProvider>
    </html>
  );
}
